---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    podsecuritypolicy.rbac.user.cattle.io/psptpb-role-binding: "true"
    serviceaccount.cluster.cattle.io/pod-security: unrestricted
  name: admission-controller-admission-controller-unrestricted-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unrestricted-clusterrole
subjects:
- kind: ServiceAccount
  name: admission-controller
  namespace: admission-controller
